version: '3.3'

volumes:
  foodgram_db:

services:

  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - foodgram_db:/var/lib/postgresql/data/
    env_file:
      - ../backend/foodgram/.env


  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
